import './globals.css'
// import { Inter } from 'next/font/google'
import { Roboto_Condensed } from 'next/font/google'

// components
import Navbar from './components/Navbar'

// const inter = Inter({ subsets: ['latin'] })
const robotoCondensed = Roboto_Condensed({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={robotoCondensed.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
